default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  user: takemefrom_user
  password: password
  port: <%= ENV["DB_PORT"] || "5496" %>

development:
  <<: *default
  database: takemefrom_development

test: &test
  <<: *default
  database: takemefrom_test

production:
  <<: *default
  database: takemefrom_production

cucumber:
  <<: *test
